branches:
  only:
    - master
    - develop
environment:
  access_key:
    secure: AKIAJIUIKUBZBXHSAR5Q
  secret_key:
    secure: 3pvBXjsWdGcaxmh5339WyN34ukiKJHyq+lfwxkyd+tfxu/0XgrQDsMfD5Uf44j+h

install:
  - cmd: npm install
build_script:
  - cmd: npm run build

artifacts:
  - path: ezipay-au
    name: ezipay-au
    type: zip
  - path: ezipay-nz
    name: ezipay-nz
    type: zip

deploy:
  - provider: S3
    access_key_id: AKIAJIUIKUBZBXHSAR5Q
    secret_access_key:
      secure: 3pvBXjsWdGcaxmh5339WyN34ukiKJHyq+lfwxkyd+tfxu/0XgrQDsMfD5Uf44j+h
    bucket: widgets.certegyezipay.com.au
    region: ap-southeast-2
    unzip: true
    set_public: true
    artifact: ezipay-au
  - provider: S3
    access_key_id: AKIAJIUIKUBZBXHSAR5Q
    secret_access_key:
      secure: 3pvBXjsWdGcaxmh5339WyN34ukiKJHyq+lfwxkyd+tfxu/0XgrQDsMfD5Uf44j+h
    bucket: widgets.certegyezipay.co.nz
    region: ap-southeast-2
    unzip: true
    set_public: true
    artifact: ezipay-nz

notifications:
  - provider: Email
    to:
      - pit@certegy.com.au
#      - devadmin@oxipay.com.au
  - provider: Slack
    auth_token:
      secure: QWE2vFI2LUFAu+jx4lXHihtpPFoVi+ru0mHSC/BvsyXYcRvgh7Tc8zEEaKkj1n5V09+Ti39CvVooS3Y8VTn7PYC6lef2OrQQ+ivqkJL+lZI=
    channel: '#alerts'
